### ISSUE TITLE
Проблема с подключениями и ПКМ

### ISSUE THREAD

**Issue by shift-reality** [retejs/connection-plugin#10]
Здравствуйте!
Подскажите, в чем может быть проблема?
Воспроизводиться так: нужно сначала открыть контекстное меню, затем нажимать ПКМ
Результат: все связи начинают пропадать, по очереди...
Браузер: firefox 60.5.1esr (64-bit)
Снимок:
![Peek 2019-03-11 09-41](https://user-images.githubusercontent.com/29734946/54107633-63f23b80-43e2-11e9-87d7-d9d23f0c7d5a.gif)

**Comment by Ni55aN** [comment]
Начиная с версии 0.4.5 проблема с отображением <path> и лишней занимаемой областью исправлены: 
1. ширина и высота SVG равны 1px, теперь он не перекрывает другие элементы
2. добавлен "магический" position: absolute, который исправляет позицию <path> при слишком маленьком размере SVG. [Подробнее](https://stackoverflow.com/questions/55110988/svg-with-width-and-height-equal-to-1px-has-a-wrong-path-position)
