### ISSUE TITLE
I have a connection problem

### ISSUE THREAD

**Issue by saalaus** [retejs/connection-plugin#11]
I have a connection problem. What caused this to happen?

I noticed that everything is fine in the browser Firefox, and in a browser Google Chrome like this:
![image](https://user-images.githubusercontent.com/37474917/47961455-209b5100-e02d-11e8-8bef-d7152401eb38.png)

**Comment by Ni55aN** [comment]
Starting with v0.4.5 the issue with displaying <path> and extra occupied area has been fixed:
1. width and height of SVG are 1px, now it doesn't overlap other elements
2. added a "magical" position: absolute that fixes a position of <path> when SVG size is very small. [Details](https://stackoverflow.com/questions/55110988/svg-with-width-and-height-equal-to-1px-has-a-wrong-path-position)
