### ISSUE TITLE
Event to detect sockets dragged but dropped on empty

### ISSUE THREAD

**Issue by Armaldio** [retejs/connection-plugin#13]
It could be useful in this scenario:

You start dragging a socket, you don't have a destination socket, so you drop the link anywhere and the context menu open. You can then choose your node and I can attach the socket to the newly created node

Example: https://youtu.be/8ew12FLgaMs?t=98

**Comment by Ni55aN** [comment]
I have added `connectiondrop` event to v0.6.3.
Currently I'm working on [plugin](https://github.com/retejs/rete/issues/261#issuecomment-467164852) that will contains this feature

**Comment by Ni55aN** [comment]
The feature [here](https://github.com/retejs/connection-mastery-plugin)

**Comment by Armaldio** [comment]
Great 👍
