### ISSUE TITLE
how to stop multiple Socket output to open from one single Socket output point

### ISSUE THREAD

**Issue by rajibprm** [retejs/connection-plugin#16]
How can I stop to open multiple socket connection from one single socket output ? 
I have made it false, but it's still opening

class NumComponent extends Rete.Component {

	constructor(){
		super("");
	}
	
	builder(node) {

		var out1 = new Rete.Output('num', node.data.name, numSocket, false);
		return node.addControl(new NumControl(this.editor, 'num', false)).addOutput(out1);
	}

	worker(node, inputs, outputs) {
		outputs['num'] = node.data.num;
	}
}

![m](https://user-images.githubusercontent.com/51480400/59101962-4a608180-8948-11e9-9cfb-f197ba5979df.png)

**Comment by Ni55aN** [comment]
In v0.8.0 you can prevent `connectionpick` event. In your case it will be

```js
editor.on('connectionpick', io => {
    if(io instanceof Rete.Output && !io.multipleConnections && io.hasConnection())
      return false; // prevent connection picking for output with exist connection and allowed only single connection
})
```
