### ISSUE TITLE
Multiple editors

### ISSUE THREAD

**Issue by mklewandowski** [retejs/connection-plugin#17]
Hi,

Is it possible to have multiple Rete editors at the same time (for example, can you create 2 divs and drop an editor in each and have them both display and function properly)?  We tried some quick tests, but have `Node view not found` errors when connecting nodes.  Any thoughts?  Many thanks!

**Comment by Ni55aN** [comment]
Fixed in v0.8.1

**Comment by Ni55aN** [comment]
I found one issue in v0.8.1: connection doesn't disappear when clicking on empty area. Fixed it in v0.8.2
