### ISSUE TITLE
Connection line

### ISSUE THREAD

**Issue by MariuszMularczyk** [retejs/connection-plugin#19]
Hi,
can connections go around the nodes and not passing through them?

![conn](https://user-images.githubusercontent.com/54709617/64692380-44bd8f00-d495-11e9-9004-eb9b7571c146.png)
![conn2](https://user-images.githubusercontent.com/54709617/64692392-48e9ac80-d495-11e9-97cf-c8b635ccd8da.png)

**Comment by Ni55aN** [comment]
Connections' path can be modified in the [next way](https://github.com/retejs/connection-reroute-plugin/blob/master/src/index.js#L7). This way you can calculate a position of points
