### ISSUE TITLE
Customize connection rendering (CSS)

### ISSUE THREAD

**Issue by WieFel** [retejs/connection-plugin#21]
For my use case I need connections between rete components to be rendered in varying ways.
Is it possible to style connections using CSS classes, depending on the input/output sockets that the connections are connected to?
At the moment I handle this by programmatically setting the style of a connection when it is rendered by the editor (and checking its socket-classes):
```
editor.on("renderconnection", ({el, connection, points}) => {
    el.setAttribute("style", "position:absolute; z-index: -2;");
}
```
(1) However, I wonder if there is a better solution to that? Dynamically adding an attribute "class" `.x` to the connection and defining that class `.x` in the `rete.component.css` file doesn't work.

In addition to this, I need one type of connection to be rendered completely different from others. I use special sockets that cover all of a components height to indicate a meta-connection between components. This connection should be wider in stroke-width and adapt its stroke width to the size of the socket of the respective component. At the moment it looks like this (with increased stroke-width and changed colour to light blue):
![actual](https://user-images.githubusercontent.com/8345062/67767630-39c4bb00-fa51-11e9-9d33-58f5c184430b.jpg)

The goal would be to start with a connection of width equal to the socket height of the origin component and then transition the connection width to the height of the socket of the target component. More or less like this (marked in red):
![desired](https://user-images.githubusercontent.com/8345062/67767908-b9eb2080-fa51-11e9-9464-2c2e412f2e40.jpg)

(2) Is it possible to achieve this with the current version of the connection-plugin?

**Comment by Ni55aN** [comment]
> Dynamically adding an attribute "class" .x to the connection and defining that class .x in the rete.component.css file doesn't work.

Styles in `rete.component.css` shouldn't be scoped

> I use special sockets that cover all of a components height to indicate a meta-connection between components

Is it real socket? I think this is a bad solution, since it is a visual part, not functional

> to start with a connection of width equal to the socket height of the origin component and then transition the connection width to the height of the socket of the target component

In this case you need a polygon (filled path), not path with a large stroke.

**Comment by WieFel** [comment]
> Styles in `rete.component.css` shouldn't be scoped
>
Could you further explain that? Because if I do
```
.socket.number-value {
    background: #96b38a
}
```
inside `rete.component.css`, wouldn't it be scoped as well?

> Is it real socket? I think this is a bad solution, since it is a visual part, not functional
> 
Yes, it is a type of socket with it's css `height` property increased. It is needed because I need two types of connections for my use case. One connection for indicating an "abstract" connection between two nodes and one indicating the flow of parameters between nodes. Therefore I try to implement the abstract connection as a broad stroke in the background using a color that is less strong. What would you recommend otherwise?

Thanks

**Comment by Ni55aN** [comment]
@WieFel if you look at the injected `<style>` in your page, you'll find `[ng-content-*]` selector. Thus, your styles inside component not working outside. This styles shoud be global

**Comment by RayBenefield** [comment]
@Ni55aN Would be really nice to be able to replace it with a custom component similar to the rest of the framework's components. I prefer the approach of scoped css with a vue component and it'd be nice to keep that pattern. Right now I just override connections with `!important` (my css skills aren't great).
