### ISSUE TITLE
Connection path position not following input/output point positions

### ISSUE THREAD

**Issue by Githamza** [retejs/connection-plugin#24]
@Ni55aN  I'm using Angular-renderer-plugin to customise nodes and vertical connections direction

paths are not centered on input/output dots position but  on `div` parent position ( I have changed `z-index` path to show better the issue

![Capture d’écran 2020-01-04 à 01 35 26](https://user-images.githubusercontent.com/11578288/71757036-3efc1700-2e93-11ea-8439-0b0ff89c066b.png)

here's the layout of my custom node

```
<div appNodeStyle [nodeType]= "node.data.typeUI" class="node" [ngClass]="[selected(), node.name] | kebab">
    <div  class="grid-container">
            <div class="params"> <mat-icon  matRipple (click)='selectNode()'>more_vert</mat-icon>     
            </div>
        <div class="title">{{node.name}}</div>
        <div class="output" *ngFor="let output of outputs">
            <rete-socket rete-socket [io]="output" [socket]="output.socket"></rete-socket>
        </div>
        
        <div class="input" *ngFor="let input of inputs">
            <rete-socket rete-socket [io]="input" [socket]="input.socket"></rete-socket>
        </div>
    </div>
</div>

```

Css

```
.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: auto auto auto;
  grid-template-areas: 'input input' 'title params' 'output output';
  grid-auto-columns: min-content;
  align-self: center;
  height: 100%;
  align-items: center;
}
.params {
  grid-area: params;
  justify-self: end;
  align-self: start;
  cursor: pointer;
}
.title {
  grid-area: title;
  align-self: start;
  justify-self: center;
}

.input {
  grid-area: input;
  justify-self: center;
  height: 0px;
}

.output {
  grid-area: output;
  justify-self: center;
}
::ng-deep .socket.output {
  margin-bottom: -28px !important;
  margin-right: 0px !important;
}
::ng-deep .socket.input {
  margin-top: -36px !important;
  margin-left: 0px !important;
}
```
Here's what I expect
![Screenshot_2020-01-04-09-40-24-039_com miui gallery](https://user-images.githubusercontent.com/11578288/71762931-40026800-2ed6-11ea-9500-8ab91193d3a6.jpg)

**Comment by Ni55aN** [comment]
https://codepen.io/Ni55aN/pen/ZMdPea?editors=0010

![image](https://user-images.githubusercontent.com/8259641/72205458-e1b42700-348b-11ea-87d9-65903507a67c.png)

[Your example](https://github.com/retejs/connection-plugin/issues/3#issuecomment-573006537):

![image](https://user-images.githubusercontent.com/8259641/72205465-f42e6080-348b-11ea-928c-5b6333a91fc3.png)

The problem also happens for horizontal connections, it’s just insensibly

Perhaps you have interfering styles, as in [this case](https://github.com/retejs/rete/issues/298#issuecomment-488093307)

**Comment by Rafarel** [comment]
Hey, did you find an answer to this?

**Comment by Ni55aN** [comment]
Hello @Rafarel, could you provide details or an example of how to reproduce it?
