### ISSUE TITLE
Curvature option doesn't seem to change anything

### ISSUE THREAD

**Issue by WieFel** [retejs/connection-plugin#26]
I am trying to change the curvature of the connections in my rete editor.
The feature to change the `curvature` of the connections is shown [here](https://rete.readthedocs.io/en/latest/Plugins/#connection).

However, regardless of setting it to a low or a high value, the connections seem to be exactly the same:
```
editor.use(ConnectionPlugin, {curvature: 0.1});
```
yields:
![curvature_0 1](https://user-images.githubusercontent.com/8345062/73930936-b3cdd100-48d7-11ea-9756-b4d2313bfb9a.png)

```
editor.use(ConnectionPlugin, {curvature: 1.0});
```
yields:
![curvature_1 0](https://user-images.githubusercontent.com/8345062/73930956-bc260c00-48d7-11ea-9e76-a571f91628e7.png)

Is this a bug or am I interpreting the `curvature` option wrongly?

**Comment by Ni55aN** [comment]
The latest ConnectionPlugin versions don't have this option

https://github.com/retejs/connection-path-plugin
