### ISSUE TITLE
Connection only goes in one way

### ISSUE THREAD

**Issue by vamidi** [retejs/connection-plugin#27]
Hi I have made nodes with multiple connections and I just want to connect the left node with the right node, but that only goes from right to left.

[EDIT] it only happens when you add multiple. if adding multiple then only the last socket works.(see second gif)

https://gyazo.com/8f0b761872c7bedc93d9f086ef26c241
[EDIT] https://gyazo.com/a22dfe44a5ca7a411f55869ba17c359f

**Comment by Ni55aN** [comment]
Maybe you have some kind of event handlers that prevent connections, because in [this example](https://codepen.io/Ni55aN/pen/xzgQYq?editors=0010) the connections work correctly

**Comment by vamidi** [comment]
Sorry forgot to close this issue. It is working fine now I had copied the whole project to my personal project and worked from there, that caused issues, but now due to the fix I reverted everything and work with the right files again.
