### ISSUE TITLE
Horizontal/vertical direction

### ISSUE THREAD

**Issue by Ni55aN** [retejs/connection-plugin#3]

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-path-plugin

Example:

```js
editor.use(ConnectionPlugin)
editor.use(ConnectionPathPlugin, { options: { vertical: true, curvature: 0.4 } })
```

**Comment by Githamza** [comment]
I have applied  these params but I would like to know if I could place sockets ( connection circles ) on top ( for inputs ) and button (for output )
https://codesandbox.io/s/retejs-angular-render-ecfyk

**Comment by Ni55aN** [comment]
@Githamza https://github.com/retejs/angular-render-plugin#custom-node
https://github.com/retejs/examples/tree/master/Angular8/src/app/rete/components/node
