### ISSUE TITLE
connection path goes under the nodes

### ISSUE THREAD

**Issue by liesislukas** [retejs/connection-plugin#44]
![image](https://user-images.githubusercontent.com/2733862/119264771-23f78780-bbed-11eb-921e-9299b94f4049.png)

Any suggestions how to make this path go around the node so it would be all visible even if node has no transparency?

**Comment by rc-dgalide** [comment]
@liesislukas `connectionPath` event exposes the `path` element. From there you can modify the connection.
```
editor.on(
      'connectionPath',
      (data: {points: number[], connection: Connection, d: string}) => {...fooBar}
    );
``` 
`points` is your connection coordinates, `d` the path property. Connection has the input & output it relates to. From there you can do pretty much anything !

**Comment by liesislukas** [comment]
Yup, already did. Just it took couple hours to resolve, was expecting to have a simple option to enable something like this.

![image](https://user-images.githubusercontent.com/2733862/120448862-a3771a80-c394-11eb-9d21-484bc1e4b8e3.png)
