### ISSUE TITLE
Disconnect a specific connection from the input with a large number of connections

### ISSUE THREAD

**Issue by Ni55aN** [retejs/connection-plugin#5]
We need a convenient way in terms of UX how to pick a certain connection. Any suggestions ?

**Comment by Clasen00** [comment]
Can also someone make some example please, to see what we are talking about? To watch the problem) If I understand right, to solve the problem we can handle dblick on each socket line to show menu with moves: "delete", "change color, "change name" for example...

**Comment by Ni55aN** [comment]
Does anyone have suggestions or remarks on this approach: https://github.com/retejs/rete/issues/177#issuecomment-436452579 ?

**Comment by RostyslavBaldovskyi** [comment]
I think will be good to have "sub" component with one input and N outputs (after adding first will created second etc.) which will attached to node and forbid multiple connections for one slocket. 
https://c2n.me/40dlqoh

Similar to hub
Using this component will help for managing connections.

Additionally about sockets. Similar to "hub" (maybe it is not related to connections)
For me it will be good to have socket with sub sockets like in menu. And i will have possibility to open it and see children. Socket can contains value (as it is now) or object with values (as tree). 
Example:
https://c2n.me/40dlnEf

I can close or open "subsockets". In case for example onFocus & onChange connected in closed mode it can be displayed with small dots with different colors.

It will be not so easy to implement but it can be helpful for further reflection :)

**Comment by Ni55aN** [comment]
> I think will be good to have "sub" component with one input and N outputs (after adding first will created second etc.) which will attached to node and forbid multiple connections for one slocket.

I don’t quite understand why an additional node is needed, since this is about the multiple connections at the entrance, not the exit

> For me it will be good to have socket with sub sockets like in menu. And i will have possibility to open it and see children. Socket can contains value (as it is now) or object with values (as tree).

This will lead to complication. Why not just keep a single list of sockets or create additional node?

**Comment by Ni55aN** [comment]
Any UX improvements to the `connection-plugin` can be implemented in a single plugin.

Suggest name
https://github.com/retejs/rete/issues/261#issuecomment-467164852

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/261#issuecomment-504767429
