### ISSUE TITLE
Can't display connections in IE11.

### ISSUE THREAD

**Issue by ahoyama** [retejs/connection-plugin#6]
Does not Rete support IE11?
I can not display connections using rete-connection-plugin in IE11.
This is because IE11 does not support svg.classList & path.classList on utils.js.
I recommend using setAttribute instead of classList.

**Comment by Ni55aN** [comment]
Ok, I'll fix it soon

**Comment by ahoyama** [comment]
Thanks!

**Comment by Ni55aN** [comment]
Using `setAttribute` makes the code dirtier, so I suggest using some kind of polyfill for IE

**Comment by ahoyama** [comment]
Thank you for the advice!
By importing "classlist-polyfill", svg.classlist is now available.
But, another problem occurred.
IE11 developer tool showed the following error:
`"Assignment to read-only properties is not allowed in strict mode" `
and, it was not possible to display the connections successfully.
(This problem occurred when using "DOM4" too)

It seems to be caused by that classList is read only property.
So, I suggest using `classList.add(...)` or `className.baseVal = ... ` on utils.js.

For example,

    classed.unshift('connection');
    svg.classList.add(...classed);
    path.classList.add('main-path');

(I don't know why we can edit classList directly in Chrome, but "https://stackoverflow.com/questions/41532463/" might be helpful to answer) 

classlist-polyfill
https://github.com/yola/classlist-polyfill

DOM4
https://github.com/WebReflection/dom4

**Comment by Ni55aN** [comment]
I have fixed this issue in v0.2.4.

Also `classList` is used in this way in other plugins (area, connection-path). Can you test it on IE?

**Comment by ahoyama** [comment]
Thanks a lot!
With "classlist-polyfill", it works on IE11.
