### ISSUE TITLE
Allow creating connections from input sockets

### ISSUE THREAD

**Issue by iKlsR** [retejs/connection-plugin#9]
It would be nice to be able to drag from an input socket to an output socket to create a connection. Rete seems to assume a linear left to right workflow but I might not want to construct my logic like that all the time and sometimes work backwards.

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-plugin/releases/tag/v0.6.0

**Comment by Ni55aN** [comment]
`connection plugin` in [example](https://codepen.io/Ni55aN/pen/xzgQYq) has been updated
